import "server-only";
import type Stripe from "stripe";
import type { Firestore } from "firebase-admin/firestore";

/* Invoices generated by Stripe, mirrored into Firestore so every payment
   leaves a record the dashboard owns: `lunaPartners/{id}/invoices/{invoiceId}`.
   The Stripe-hosted PDF link is stored alongside, so the Download button
   works even when the row came out of the cache. */

export interface StoredInvoice {
  id: string;
  /** Human number like INV-0001 (falls back to the Stripe id). */
  number: string;
  status: "paid" | "due" | "void";
  /** Total in cents. */
  amount: number;
  currency: string;
  /** Unix seconds. */
  created: number;
  periodStart: number;
  periodEnd: number;
  hostedInvoiceUrl: string | null;
  invoicePdf: string | null;
}

export function toStoredInvoice(inv: Stripe.Invoice): StoredInvoice {
  return {
    id: inv.id ?? "",
    number: inv.number ?? inv.id ?? "",
    status: inv.status === "paid" ? "paid" : inv.status === "void" ? "void" : "due",
    amount: inv.amount_due,
    currency: inv.currency,
    created: inv.created,
    periodStart: inv.period_start ?? inv.created,
    periodEnd: inv.period_end ?? inv.created,
    hostedInvoiceUrl: inv.hosted_invoice_url ?? null,
    invoicePdf: inv.invoice_pdf ?? null,
  };
}

/** Upsert one invoice under the partner profile. */
export async function storeInvoice(
  db: Firestore,
  partnerId: string,
  invoice: StoredInvoice
): Promise<void> {
  if (!invoice.id) return;
  await db
    .collection("lunaPartners")
    .doc(partnerId)
    .collection("invoices")
    .doc(invoice.id)
    .set(invoice, { merge: true });
}

/** Pull the customer's invoices from Stripe, mirror them into Firestore
    (best effort), and return them newest-first. */
export async function syncInvoicesFromStripe(
  db: Firestore,
  partnerId: string,
  stripe: Stripe,
  customerId: string
): Promise<StoredInvoice[]> {
  const list = await stripe.invoices.list({ customer: customerId, limit: 24 });
  const invoices = list.data
    .filter((inv) => inv.status !== "draft")
    .map(toStoredInvoice);
  await Promise.all(
    invoices.map((inv) => storeInvoice(db, partnerId, inv).catch(() => undefined))
  );
  return invoices;
}

/** Read the mirrored invoices for a partner, newest-first. */
export async function readStoredInvoices(
  db: Firestore,
  partnerId: string
): Promise<StoredInvoice[]> {
  const snap = await db
    .collection("lunaPartners")
    .doc(partnerId)
    .collection("invoices")
    .orderBy("created", "desc")
    .limit(24)
    .get();
  return snap.docs.map((d) => d.data() as StoredInvoice);
}
